// Catálogo inicial importado de la lista de precios del proveedor
// Roberto Pérez Lucio (Paradice), 14 de septiembre 2026.
// NOTA: solo se importaron nombres y unidad — sin precios, ya que cambian
// cada semana (ver src/lib/productos.ts). Sofia debe confirmar cuáles de
// estos productos sí vende El Wero (por eso arrancan como no disponibles).
import type { Unidad } from "./remisiones";

export interface ProductoSeed {
  nombre: string;
  unidad: Unidad;
  proveedor: string;
}

export const PRODUCTOS_SEED: ProductoSeed[] = [
  { nombre: "Acelgas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Aguacate Hass", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Aguacate Hass Super Extra", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ajo Macho", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ajo Pelado", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ajonjoli", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ajos del 10", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Albahaca", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Alcachofas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Apio", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Arandano", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Arugula", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Azucar Piloncillo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Berenjena", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Betabel", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Blueberry moras", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Brocoli Verde", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Brote de alfalfa 200 grs", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Brote de betabel 200 grs", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Brote de cilantro 50 gr", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cacahuate", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Calabaza castilla", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Calabaza Italiana", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Calabaza local", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Camote Amarillo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Canela en raja", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebada", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Blanca Jumbo Pelada", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Blanca MG", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Cambray", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Cambray c/rabo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Cambray S/Rabo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebolla Morada", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cebollín", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Champiñon Blanco", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chaya", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chayote", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chicharo japonés", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Ancho", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Arbol", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile chipotle", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile dulce", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Guajillo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Habanero", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Jalapeño", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Morita", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Mulato", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Pasilla", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Poblano", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Puya", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Serrano", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Chile Xcatic", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cilantro local", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Cilantro Mexico", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ciruela Natural", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ciruela Pasa a/hueso", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Clavo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Coco", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Coco rayado", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Col Morada", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Coliflor", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Durazno", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Echalote", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Ejote", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Elote", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Elote desgranado", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Elote limpio y pelado", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Epazote", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Espinaca", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Espinaca Baby", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Espárragos", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Flor de Jamaica", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Frambuesa", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Frambuesa domos", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "FRESAS", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Garbanzo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Germen de Soya", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Guayabas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hierbabuena", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Higo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hoja de Aguacate", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hoja de cambray", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hoja de Platano", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hongos de setas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Hongos Portobello", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Huevo Blanco", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Jengibre", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Jicama", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Jitomate Bola", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Jitomate Cherry", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Kiwi", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Laurel", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga chicoria", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga Escarola", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga francesa", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga Italina", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga Orejona", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga Romana", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lechuga Sangria", unidad: "pieza", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Lima", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Limon eureka", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Limon Verde sin semilla", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Mango ataulfo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Manzana Gala", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Manzana Golden", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Manzana Granny Smith", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Manzana Starkyn americana", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Melones Chinos", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Melones Chinos # 9", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Melones Valencianos #9", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Nabo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Naranja agria", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Naranja Dulce Local", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Naranja Valenciana", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Nopal Limpio", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Nuez de la India", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Nuez Pecana en mitad", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Nuez Pecana trozada", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Oregano Entero", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Oregano Molido", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pan molido", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Papa Alpha", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Papa Alpha Jumbo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Papa Cambray", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Papaya Maradol", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pasitas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pepino Verde", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pepita semilla", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pera", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Perejil Chino", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Perejil LISO", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimienta Castilla", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimienta Molida", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimienta Tabasco", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimiento Morron Amarillo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimiento Morron Rojo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pimiento Morron Verde", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Piña Miel", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Platano Macho", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Platano Roatan", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Poros", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Pulpa de Maracuya", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Rabano Sandia", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Rabanos", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Repollo", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Romero", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Sandias", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Tomate Saladet de 1a", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Tomate Saladet de 2a", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Tomate Verde", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Toronjas", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Uva roja", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Uva Verde", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Zanahoria", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Zarzamora", unidad: "domo", proveedor: "Roberto Pérez Lucio (Paradice)" },
  { nombre: "Zarzamora domos", unidad: "kg", proveedor: "Roberto Pérez Lucio (Paradice)" },
];
